[project]
name = "conversation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=0.2.0",
    "google-genai>=1.11.0",
]
